// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: BillDanmu.proto
// Protobuf Java Version: 4.29.2

package com.github.tvbox.osc.player.danmu;

public final class BillDanmuEntity {
  private BillDanmuEntity() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 2,
      /* suffix= */ "",
      BillDanmuEntity.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface DanmuOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.github.catvod.bean.bili.Danmu)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    long getId();

    /**
     * <code>int32 progress = 2;</code>
     * @return The progress.
     */
    int getProgress();

    /**
     * <code>int32 mode = 3;</code>
     * @return The mode.
     */
    int getMode();

    /**
     * <code>int32 fontsize = 4;</code>
     * @return The fontsize.
     */
    int getFontsize();

    /**
     * <code>uint32 color = 5;</code>
     * @return The color.
     */
    int getColor();

    /**
     * <code>string midHash = 6;</code>
     * @return The midHash.
     */
    String getMidHash();
    /**
     * <code>string midHash = 6;</code>
     * @return The bytes for midHash.
     */
    com.google.protobuf.ByteString
        getMidHashBytes();

    /**
     * <code>string content = 7;</code>
     * @return The content.
     */
    String getContent();
    /**
     * <code>string content = 7;</code>
     * @return The bytes for content.
     */
    com.google.protobuf.ByteString
        getContentBytes();

    /**
     * <code>int64 ctime = 8;</code>
     * @return The ctime.
     */
    long getCtime();

    /**
     * <code>int32 weight = 9;</code>
     * @return The weight.
     */
    int getWeight();

    /**
     * <code>string action = 10;</code>
     * @return The action.
     */
    String getAction();
    /**
     * <code>string action = 10;</code>
     * @return The bytes for action.
     */
    com.google.protobuf.ByteString
        getActionBytes();

    /**
     * <code>int32 pool = 11;</code>
     * @return The pool.
     */
    int getPool();

    /**
     * <code>string idStr = 12;</code>
     * @return The idStr.
     */
    String getIdStr();
    /**
     * <code>string idStr = 12;</code>
     * @return The bytes for idStr.
     */
    com.google.protobuf.ByteString
        getIdStrBytes();

    /**
     * <code>int32 attr = 13;</code>
     * @return The attr.
     */
    int getAttr();

    /**
     * <code>string effect = 22;</code>
     * @return The effect.
     */
    String getEffect();
    /**
     * <code>string effect = 22;</code>
     * @return The bytes for effect.
     */
    com.google.protobuf.ByteString
        getEffectBytes();
  }
  /**
   * Protobuf type {@code com.github.catvod.bean.bili.Danmu}
   */
  public static final class Danmu extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.github.catvod.bean.bili.Danmu)
      DanmuOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 2,
        /* suffix= */ "",
        Danmu.class.getName());
    }
    // Use Danmu.newBuilder() to construct.
    private Danmu(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Danmu() {
      midHash_ = "";
      content_ = "";
      action_ = "";
      idStr_ = "";
      effect_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return BillDanmuEntity.internal_static_com_github_catvod_bean_bili_Danmu_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return BillDanmuEntity.internal_static_com_github_catvod_bean_bili_Danmu_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Danmu.class, Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private long id_ = 0L;
    /**
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    @Override
    public long getId() {
      return id_;
    }

    public static final int PROGRESS_FIELD_NUMBER = 2;
    private int progress_ = 0;
    /**
     * <code>int32 progress = 2;</code>
     * @return The progress.
     */
    @Override
    public int getProgress() {
      return progress_;
    }

    public static final int MODE_FIELD_NUMBER = 3;
    private int mode_ = 0;
    /**
     * <code>int32 mode = 3;</code>
     * @return The mode.
     */
    @Override
    public int getMode() {
      return mode_;
    }

    public static final int FONTSIZE_FIELD_NUMBER = 4;
    private int fontsize_ = 0;
    /**
     * <code>int32 fontsize = 4;</code>
     * @return The fontsize.
     */
    @Override
    public int getFontsize() {
      return fontsize_;
    }

    public static final int COLOR_FIELD_NUMBER = 5;
    private int color_ = 0;
    /**
     * <code>uint32 color = 5;</code>
     * @return The color.
     */
    @Override
    public int getColor() {
      return color_;
    }

    public static final int MIDHASH_FIELD_NUMBER = 6;
    @SuppressWarnings("serial")
    private volatile Object midHash_ = "";
    /**
     * <code>string midHash = 6;</code>
     * @return The midHash.
     */
    @Override
    public String getMidHash() {
      Object ref = midHash_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        midHash_ = s;
        return s;
      }
    }
    /**
     * <code>string midHash = 6;</code>
     * @return The bytes for midHash.
     */
    @Override
    public com.google.protobuf.ByteString
        getMidHashBytes() {
      Object ref = midHash_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        midHash_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CONTENT_FIELD_NUMBER = 7;
    @SuppressWarnings("serial")
    private volatile Object content_ = "";
    /**
     * <code>string content = 7;</code>
     * @return The content.
     */
    @Override
    public String getContent() {
      Object ref = content_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        content_ = s;
        return s;
      }
    }
    /**
     * <code>string content = 7;</code>
     * @return The bytes for content.
     */
    @Override
    public com.google.protobuf.ByteString
        getContentBytes() {
      Object ref = content_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CTIME_FIELD_NUMBER = 8;
    private long ctime_ = 0L;
    /**
     * <code>int64 ctime = 8;</code>
     * @return The ctime.
     */
    @Override
    public long getCtime() {
      return ctime_;
    }

    public static final int WEIGHT_FIELD_NUMBER = 9;
    private int weight_ = 0;
    /**
     * <code>int32 weight = 9;</code>
     * @return The weight.
     */
    @Override
    public int getWeight() {
      return weight_;
    }

    public static final int ACTION_FIELD_NUMBER = 10;
    @SuppressWarnings("serial")
    private volatile Object action_ = "";
    /**
     * <code>string action = 10;</code>
     * @return The action.
     */
    @Override
    public String getAction() {
      Object ref = action_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        action_ = s;
        return s;
      }
    }
    /**
     * <code>string action = 10;</code>
     * @return The bytes for action.
     */
    @Override
    public com.google.protobuf.ByteString
        getActionBytes() {
      Object ref = action_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        action_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int POOL_FIELD_NUMBER = 11;
    private int pool_ = 0;
    /**
     * <code>int32 pool = 11;</code>
     * @return The pool.
     */
    @Override
    public int getPool() {
      return pool_;
    }

    public static final int IDSTR_FIELD_NUMBER = 12;
    @SuppressWarnings("serial")
    private volatile Object idStr_ = "";
    /**
     * <code>string idStr = 12;</code>
     * @return The idStr.
     */
    @Override
    public String getIdStr() {
      Object ref = idStr_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        idStr_ = s;
        return s;
      }
    }
    /**
     * <code>string idStr = 12;</code>
     * @return The bytes for idStr.
     */
    @Override
    public com.google.protobuf.ByteString
        getIdStrBytes() {
      Object ref = idStr_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        idStr_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ATTR_FIELD_NUMBER = 13;
    private int attr_ = 0;
    /**
     * <code>int32 attr = 13;</code>
     * @return The attr.
     */
    @Override
    public int getAttr() {
      return attr_;
    }

    public static final int EFFECT_FIELD_NUMBER = 22;
    @SuppressWarnings("serial")
    private volatile Object effect_ = "";
    /**
     * <code>string effect = 22;</code>
     * @return The effect.
     */
    @Override
    public String getEffect() {
      Object ref = effect_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        effect_ = s;
        return s;
      }
    }
    /**
     * <code>string effect = 22;</code>
     * @return The bytes for effect.
     */
    @Override
    public com.google.protobuf.ByteString
        getEffectBytes() {
      Object ref = effect_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        effect_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0L) {
        output.writeInt64(1, id_);
      }
      if (progress_ != 0) {
        output.writeInt32(2, progress_);
      }
      if (mode_ != 0) {
        output.writeInt32(3, mode_);
      }
      if (fontsize_ != 0) {
        output.writeInt32(4, fontsize_);
      }
      if (color_ != 0) {
        output.writeUInt32(5, color_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(midHash_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 6, midHash_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(content_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 7, content_);
      }
      if (ctime_ != 0L) {
        output.writeInt64(8, ctime_);
      }
      if (weight_ != 0) {
        output.writeInt32(9, weight_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(action_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 10, action_);
      }
      if (pool_ != 0) {
        output.writeInt32(11, pool_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(idStr_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 12, idStr_);
      }
      if (attr_ != 0) {
        output.writeInt32(13, attr_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(effect_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 22, effect_);
      }
      getUnknownFields().writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (progress_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, progress_);
      }
      if (mode_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, mode_);
      }
      if (fontsize_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, fontsize_);
      }
      if (color_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(5, color_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(midHash_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(6, midHash_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(content_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(7, content_);
      }
      if (ctime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(8, ctime_);
      }
      if (weight_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(9, weight_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(action_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(10, action_);
      }
      if (pool_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(11, pool_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(idStr_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(12, idStr_);
      }
      if (attr_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(13, attr_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(effect_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(22, effect_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Danmu)) {
        return super.equals(obj);
      }
      Danmu other = (Danmu) obj;

      if (getId()
          != other.getId()) return false;
      if (getProgress()
          != other.getProgress()) return false;
      if (getMode()
          != other.getMode()) return false;
      if (getFontsize()
          != other.getFontsize()) return false;
      if (getColor()
          != other.getColor()) return false;
      if (!getMidHash()
          .equals(other.getMidHash())) return false;
      if (!getContent()
          .equals(other.getContent())) return false;
      if (getCtime()
          != other.getCtime()) return false;
      if (getWeight()
          != other.getWeight()) return false;
      if (!getAction()
          .equals(other.getAction())) return false;
      if (getPool()
          != other.getPool()) return false;
      if (!getIdStr()
          .equals(other.getIdStr())) return false;
      if (getAttr()
          != other.getAttr()) return false;
      if (!getEffect()
          .equals(other.getEffect())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getId());
      hash = (37 * hash) + PROGRESS_FIELD_NUMBER;
      hash = (53 * hash) + getProgress();
      hash = (37 * hash) + MODE_FIELD_NUMBER;
      hash = (53 * hash) + getMode();
      hash = (37 * hash) + FONTSIZE_FIELD_NUMBER;
      hash = (53 * hash) + getFontsize();
      hash = (37 * hash) + COLOR_FIELD_NUMBER;
      hash = (53 * hash) + getColor();
      hash = (37 * hash) + MIDHASH_FIELD_NUMBER;
      hash = (53 * hash) + getMidHash().hashCode();
      hash = (37 * hash) + CONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getContent().hashCode();
      hash = (37 * hash) + CTIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getCtime());
      hash = (37 * hash) + WEIGHT_FIELD_NUMBER;
      hash = (53 * hash) + getWeight();
      hash = (37 * hash) + ACTION_FIELD_NUMBER;
      hash = (53 * hash) + getAction().hashCode();
      hash = (37 * hash) + POOL_FIELD_NUMBER;
      hash = (53 * hash) + getPool();
      hash = (37 * hash) + IDSTR_FIELD_NUMBER;
      hash = (53 * hash) + getIdStr().hashCode();
      hash = (37 * hash) + ATTR_FIELD_NUMBER;
      hash = (53 * hash) + getAttr();
      hash = (37 * hash) + EFFECT_FIELD_NUMBER;
      hash = (53 * hash) + getEffect().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Danmu parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Danmu parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Danmu parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Danmu parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Danmu parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Danmu parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Danmu parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static Danmu parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static Danmu parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static Danmu parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Danmu parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static Danmu parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Danmu prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.github.catvod.bean.bili.Danmu}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.github.catvod.bean.bili.Danmu)
        DanmuOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return BillDanmuEntity.internal_static_com_github_catvod_bean_bili_Danmu_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return BillDanmuEntity.internal_static_com_github_catvod_bean_bili_Danmu_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Danmu.class, Builder.class);
      }

      // Construct using com.github.catvod.spider.BillDanmuEntity.Danmu.newBuilder()
      private Builder() {

      }

      private Builder(
          BuilderParent parent) {
        super(parent);

      }
      @Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        id_ = 0L;
        progress_ = 0;
        mode_ = 0;
        fontsize_ = 0;
        color_ = 0;
        midHash_ = "";
        content_ = "";
        ctime_ = 0L;
        weight_ = 0;
        action_ = "";
        pool_ = 0;
        idStr_ = "";
        attr_ = 0;
        effect_ = "";
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return BillDanmuEntity.internal_static_com_github_catvod_bean_bili_Danmu_descriptor;
      }

      @Override
      public Danmu getDefaultInstanceForType() {
        return Danmu.getDefaultInstance();
      }

      @Override
      public Danmu build() {
        Danmu result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public Danmu buildPartial() {
        Danmu result = new Danmu(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(Danmu result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.id_ = id_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.progress_ = progress_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.mode_ = mode_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.fontsize_ = fontsize_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.color_ = color_;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.midHash_ = midHash_;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.content_ = content_;
        }
        if (((from_bitField0_ & 0x00000080) != 0)) {
          result.ctime_ = ctime_;
        }
        if (((from_bitField0_ & 0x00000100) != 0)) {
          result.weight_ = weight_;
        }
        if (((from_bitField0_ & 0x00000200) != 0)) {
          result.action_ = action_;
        }
        if (((from_bitField0_ & 0x00000400) != 0)) {
          result.pool_ = pool_;
        }
        if (((from_bitField0_ & 0x00000800) != 0)) {
          result.idStr_ = idStr_;
        }
        if (((from_bitField0_ & 0x00001000) != 0)) {
          result.attr_ = attr_;
        }
        if (((from_bitField0_ & 0x00002000) != 0)) {
          result.effect_ = effect_;
        }
      }

      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Danmu) {
          return mergeFrom((Danmu)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Danmu other) {
        if (other == Danmu.getDefaultInstance()) return this;
        if (other.getId() != 0L) {
          setId(other.getId());
        }
        if (other.getProgress() != 0) {
          setProgress(other.getProgress());
        }
        if (other.getMode() != 0) {
          setMode(other.getMode());
        }
        if (other.getFontsize() != 0) {
          setFontsize(other.getFontsize());
        }
        if (other.getColor() != 0) {
          setColor(other.getColor());
        }
        if (!other.getMidHash().isEmpty()) {
          midHash_ = other.midHash_;
          bitField0_ |= 0x00000020;
          onChanged();
        }
        if (!other.getContent().isEmpty()) {
          content_ = other.content_;
          bitField0_ |= 0x00000040;
          onChanged();
        }
        if (other.getCtime() != 0L) {
          setCtime(other.getCtime());
        }
        if (other.getWeight() != 0) {
          setWeight(other.getWeight());
        }
        if (!other.getAction().isEmpty()) {
          action_ = other.action_;
          bitField0_ |= 0x00000200;
          onChanged();
        }
        if (other.getPool() != 0) {
          setPool(other.getPool());
        }
        if (!other.getIdStr().isEmpty()) {
          idStr_ = other.idStr_;
          bitField0_ |= 0x00000800;
          onChanged();
        }
        if (other.getAttr() != 0) {
          setAttr(other.getAttr());
        }
        if (!other.getEffect().isEmpty()) {
          effect_ = other.effect_;
          bitField0_ |= 0x00002000;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                id_ = input.readInt64();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                progress_ = input.readInt32();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 24: {
                mode_ = input.readInt32();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              case 32: {
                fontsize_ = input.readInt32();
                bitField0_ |= 0x00000008;
                break;
              } // case 32
              case 40: {
                color_ = input.readUInt32();
                bitField0_ |= 0x00000010;
                break;
              } // case 40
              case 50: {
                midHash_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000020;
                break;
              } // case 50
              case 58: {
                content_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000040;
                break;
              } // case 58
              case 64: {
                ctime_ = input.readInt64();
                bitField0_ |= 0x00000080;
                break;
              } // case 64
              case 72: {
                weight_ = input.readInt32();
                bitField0_ |= 0x00000100;
                break;
              } // case 72
              case 82: {
                action_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000200;
                break;
              } // case 82
              case 88: {
                pool_ = input.readInt32();
                bitField0_ |= 0x00000400;
                break;
              } // case 88
              case 98: {
                idStr_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000800;
                break;
              } // case 98
              case 104: {
                attr_ = input.readInt32();
                bitField0_ |= 0x00001000;
                break;
              } // case 104
              case 178: {
                effect_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00002000;
                break;
              } // case 178
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private long id_ ;
      /**
       * <code>int64 id = 1;</code>
       * @return The id.
       */
      @Override
      public long getId() {
        return id_;
      }
      /**
       * <code>int64 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(long value) {

        id_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int64 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0L;
        onChanged();
        return this;
      }

      private int progress_ ;
      /**
       * <code>int32 progress = 2;</code>
       * @return The progress.
       */
      @Override
      public int getProgress() {
        return progress_;
      }
      /**
       * <code>int32 progress = 2;</code>
       * @param value The progress to set.
       * @return This builder for chaining.
       */
      public Builder setProgress(int value) {

        progress_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>int32 progress = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearProgress() {
        bitField0_ = (bitField0_ & ~0x00000002);
        progress_ = 0;
        onChanged();
        return this;
      }

      private int mode_ ;
      /**
       * <code>int32 mode = 3;</code>
       * @return The mode.
       */
      @Override
      public int getMode() {
        return mode_;
      }
      /**
       * <code>int32 mode = 3;</code>
       * @param value The mode to set.
       * @return This builder for chaining.
       */
      public Builder setMode(int value) {

        mode_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>int32 mode = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearMode() {
        bitField0_ = (bitField0_ & ~0x00000004);
        mode_ = 0;
        onChanged();
        return this;
      }

      private int fontsize_ ;
      /**
       * <code>int32 fontsize = 4;</code>
       * @return The fontsize.
       */
      @Override
      public int getFontsize() {
        return fontsize_;
      }
      /**
       * <code>int32 fontsize = 4;</code>
       * @param value The fontsize to set.
       * @return This builder for chaining.
       */
      public Builder setFontsize(int value) {

        fontsize_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>int32 fontsize = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearFontsize() {
        bitField0_ = (bitField0_ & ~0x00000008);
        fontsize_ = 0;
        onChanged();
        return this;
      }

      private int color_ ;
      /**
       * <code>uint32 color = 5;</code>
       * @return The color.
       */
      @Override
      public int getColor() {
        return color_;
      }
      /**
       * <code>uint32 color = 5;</code>
       * @param value The color to set.
       * @return This builder for chaining.
       */
      public Builder setColor(int value) {

        color_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 color = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearColor() {
        bitField0_ = (bitField0_ & ~0x00000010);
        color_ = 0;
        onChanged();
        return this;
      }

      private Object midHash_ = "";
      /**
       * <code>string midHash = 6;</code>
       * @return The midHash.
       */
      public String getMidHash() {
        Object ref = midHash_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          midHash_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string midHash = 6;</code>
       * @return The bytes for midHash.
       */
      public com.google.protobuf.ByteString
          getMidHashBytes() {
        Object ref = midHash_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          midHash_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string midHash = 6;</code>
       * @param value The midHash to set.
       * @return This builder for chaining.
       */
      public Builder setMidHash(
          String value) {
        if (value == null) { throw new NullPointerException(); }
        midHash_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>string midHash = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearMidHash() {
        midHash_ = getDefaultInstance().getMidHash();
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
        return this;
      }
      /**
       * <code>string midHash = 6;</code>
       * @param value The bytes for midHash to set.
       * @return This builder for chaining.
       */
      public Builder setMidHashBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        midHash_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }

      private Object content_ = "";
      /**
       * <code>string content = 7;</code>
       * @return The content.
       */
      public String getContent() {
        Object ref = content_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          content_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string content = 7;</code>
       * @return The bytes for content.
       */
      public com.google.protobuf.ByteString
          getContentBytes() {
        Object ref = content_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          content_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string content = 7;</code>
       * @param value The content to set.
       * @return This builder for chaining.
       */
      public Builder setContent(
          String value) {
        if (value == null) { throw new NullPointerException(); }
        content_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      /**
       * <code>string content = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearContent() {
        content_ = getDefaultInstance().getContent();
        bitField0_ = (bitField0_ & ~0x00000040);
        onChanged();
        return this;
      }
      /**
       * <code>string content = 7;</code>
       * @param value The bytes for content to set.
       * @return This builder for chaining.
       */
      public Builder setContentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        content_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }

      private long ctime_ ;
      /**
       * <code>int64 ctime = 8;</code>
       * @return The ctime.
       */
      @Override
      public long getCtime() {
        return ctime_;
      }
      /**
       * <code>int64 ctime = 8;</code>
       * @param value The ctime to set.
       * @return This builder for chaining.
       */
      public Builder setCtime(long value) {

        ctime_ = value;
        bitField0_ |= 0x00000080;
        onChanged();
        return this;
      }
      /**
       * <code>int64 ctime = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearCtime() {
        bitField0_ = (bitField0_ & ~0x00000080);
        ctime_ = 0L;
        onChanged();
        return this;
      }

      private int weight_ ;
      /**
       * <code>int32 weight = 9;</code>
       * @return The weight.
       */
      @Override
      public int getWeight() {
        return weight_;
      }
      /**
       * <code>int32 weight = 9;</code>
       * @param value The weight to set.
       * @return This builder for chaining.
       */
      public Builder setWeight(int value) {

        weight_ = value;
        bitField0_ |= 0x00000100;
        onChanged();
        return this;
      }
      /**
       * <code>int32 weight = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearWeight() {
        bitField0_ = (bitField0_ & ~0x00000100);
        weight_ = 0;
        onChanged();
        return this;
      }

      private Object action_ = "";
      /**
       * <code>string action = 10;</code>
       * @return The action.
       */
      public String getAction() {
        Object ref = action_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          action_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string action = 10;</code>
       * @return The bytes for action.
       */
      public com.google.protobuf.ByteString
          getActionBytes() {
        Object ref = action_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          action_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string action = 10;</code>
       * @param value The action to set.
       * @return This builder for chaining.
       */
      public Builder setAction(
          String value) {
        if (value == null) { throw new NullPointerException(); }
        action_ = value;
        bitField0_ |= 0x00000200;
        onChanged();
        return this;
      }
      /**
       * <code>string action = 10;</code>
       * @return This builder for chaining.
       */
      public Builder clearAction() {
        action_ = getDefaultInstance().getAction();
        bitField0_ = (bitField0_ & ~0x00000200);
        onChanged();
        return this;
      }
      /**
       * <code>string action = 10;</code>
       * @param value The bytes for action to set.
       * @return This builder for chaining.
       */
      public Builder setActionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        action_ = value;
        bitField0_ |= 0x00000200;
        onChanged();
        return this;
      }

      private int pool_ ;
      /**
       * <code>int32 pool = 11;</code>
       * @return The pool.
       */
      @Override
      public int getPool() {
        return pool_;
      }
      /**
       * <code>int32 pool = 11;</code>
       * @param value The pool to set.
       * @return This builder for chaining.
       */
      public Builder setPool(int value) {

        pool_ = value;
        bitField0_ |= 0x00000400;
        onChanged();
        return this;
      }
      /**
       * <code>int32 pool = 11;</code>
       * @return This builder for chaining.
       */
      public Builder clearPool() {
        bitField0_ = (bitField0_ & ~0x00000400);
        pool_ = 0;
        onChanged();
        return this;
      }

      private Object idStr_ = "";
      /**
       * <code>string idStr = 12;</code>
       * @return The idStr.
       */
      public String getIdStr() {
        Object ref = idStr_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          idStr_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string idStr = 12;</code>
       * @return The bytes for idStr.
       */
      public com.google.protobuf.ByteString
          getIdStrBytes() {
        Object ref = idStr_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          idStr_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string idStr = 12;</code>
       * @param value The idStr to set.
       * @return This builder for chaining.
       */
      public Builder setIdStr(
          String value) {
        if (value == null) { throw new NullPointerException(); }
        idStr_ = value;
        bitField0_ |= 0x00000800;
        onChanged();
        return this;
      }
      /**
       * <code>string idStr = 12;</code>
       * @return This builder for chaining.
       */
      public Builder clearIdStr() {
        idStr_ = getDefaultInstance().getIdStr();
        bitField0_ = (bitField0_ & ~0x00000800);
        onChanged();
        return this;
      }
      /**
       * <code>string idStr = 12;</code>
       * @param value The bytes for idStr to set.
       * @return This builder for chaining.
       */
      public Builder setIdStrBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        idStr_ = value;
        bitField0_ |= 0x00000800;
        onChanged();
        return this;
      }

      private int attr_ ;
      /**
       * <code>int32 attr = 13;</code>
       * @return The attr.
       */
      @Override
      public int getAttr() {
        return attr_;
      }
      /**
       * <code>int32 attr = 13;</code>
       * @param value The attr to set.
       * @return This builder for chaining.
       */
      public Builder setAttr(int value) {

        attr_ = value;
        bitField0_ |= 0x00001000;
        onChanged();
        return this;
      }
      /**
       * <code>int32 attr = 13;</code>
       * @return This builder for chaining.
       */
      public Builder clearAttr() {
        bitField0_ = (bitField0_ & ~0x00001000);
        attr_ = 0;
        onChanged();
        return this;
      }

      private Object effect_ = "";
      /**
       * <code>string effect = 22;</code>
       * @return The effect.
       */
      public String getEffect() {
        Object ref = effect_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          effect_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string effect = 22;</code>
       * @return The bytes for effect.
       */
      public com.google.protobuf.ByteString
          getEffectBytes() {
        Object ref = effect_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          effect_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string effect = 22;</code>
       * @param value The effect to set.
       * @return This builder for chaining.
       */
      public Builder setEffect(
          String value) {
        if (value == null) { throw new NullPointerException(); }
        effect_ = value;
        bitField0_ |= 0x00002000;
        onChanged();
        return this;
      }
      /**
       * <code>string effect = 22;</code>
       * @return This builder for chaining.
       */
      public Builder clearEffect() {
        effect_ = getDefaultInstance().getEffect();
        bitField0_ = (bitField0_ & ~0x00002000);
        onChanged();
        return this;
      }
      /**
       * <code>string effect = 22;</code>
       * @param value The bytes for effect to set.
       * @return This builder for chaining.
       */
      public Builder setEffectBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        effect_ = value;
        bitField0_ |= 0x00002000;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.github.catvod.bean.bili.Danmu)
    }

    // @@protoc_insertion_point(class_scope:com.github.catvod.bean.bili.Danmu)
    private static final Danmu DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Danmu();
    }

    public static Danmu getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Danmu>
        PARSER = new com.google.protobuf.AbstractParser<Danmu>() {
      @Override
      public Danmu parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Danmu> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Danmu> getParserForType() {
      return PARSER;
    }

    @Override
    public Danmu getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface DanmusOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.github.catvod.bean.bili.Danmus)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .com.github.catvod.bean.bili.Danmu danmus = 1;</code>
     */
    java.util.List<Danmu>
        getDanmusList();
    /**
     * <code>repeated .com.github.catvod.bean.bili.Danmu danmus = 1;</code>
     */
    Danmu getDanmus(int index);
    /**
     * <code>repeated .com.github.catvod.bean.bili.Danmu danmus = 1;</code>
     */
    int getDanmusCount();
    /**
     * <code>repeated .com.github.catvod.bean.bili.Danmu danmus = 1;</code>
     */
    java.util.List<? extends DanmuOrBuilder>
        getDanmusOrBuilderList();
    /**
     * <code>repeated .com.github.catvod.bean.bili.Danmu danmus = 1;</code>
     */
    DanmuOrBuilder getDanmusOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code com.github.catvod.bean.bili.Danmus}
   */
  public static final class Danmus extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.github.catvod.bean.bili.Danmus)
      DanmusOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 2,
        /* suffix= */ "",
        Danmus.class.getName());
    }
    // Use Danmus.newBuilder() to construct.
    private Danmus(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Danmus() {
      danmus_ = java.util.Collections.emptyList();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return BillDanmuEntity.internal_static_com_github_catvod_bean_bili_Danmus_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return BillDanmuEntity.internal_static_com_github_catvod_bean_bili_Danmus_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Danmus.class, Builder.class);
    }

    public static final int DANMUS_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private java.util.List<Danmu> danmus_;
    /**
     * <code>repeated .com.github.catvod.bean.bili.Danmu danmus = 1;</code>
     */
    @Override
    public java.util.List<Danmu> getDanmusList() {
      return danmus_;
    }
    /**
     * <code>repeated .com.github.catvod.bean.bili.Danmu danmus = 1;</code>
     */
    @Override
    public java.util.List<? extends DanmuOrBuilder>
        getDanmusOrBuilderList() {
      return danmus_;
    }
    /**
     * <code>repeated .com.github.catvod.bean.bili.Danmu danmus = 1;</code>
     */
    @Override
    public int getDanmusCount() {
      return danmus_.size();
    }
    /**
     * <code>repeated .com.github.catvod.bean.bili.Danmu danmus = 1;</code>
     */
    @Override
    public Danmu getDanmus(int index) {
      return danmus_.get(index);
    }
    /**
     * <code>repeated .com.github.catvod.bean.bili.Danmu danmus = 1;</code>
     */
    @Override
    public DanmuOrBuilder getDanmusOrBuilder(
        int index) {
      return danmus_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < danmus_.size(); i++) {
        output.writeMessage(1, danmus_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < danmus_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, danmus_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Danmus)) {
        return super.equals(obj);
      }
      Danmus other = (Danmus) obj;

      if (!getDanmusList()
          .equals(other.getDanmusList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getDanmusCount() > 0) {
        hash = (37 * hash) + DANMUS_FIELD_NUMBER;
        hash = (53 * hash) + getDanmusList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Danmus parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Danmus parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Danmus parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Danmus parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Danmus parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Danmus parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Danmus parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static Danmus parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static Danmus parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static Danmus parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Danmus parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static Danmus parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Danmus prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.github.catvod.bean.bili.Danmus}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.github.catvod.bean.bili.Danmus)
        DanmusOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return BillDanmuEntity.internal_static_com_github_catvod_bean_bili_Danmus_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return BillDanmuEntity.internal_static_com_github_catvod_bean_bili_Danmus_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Danmus.class, Builder.class);
      }

      // Construct using com.github.catvod.spider.BillDanmuEntity.Danmus.newBuilder()
      private Builder() {

      }

      private Builder(
          BuilderParent parent) {
        super(parent);

      }
      @Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        if (danmusBuilder_ == null) {
          danmus_ = java.util.Collections.emptyList();
        } else {
          danmus_ = null;
          danmusBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return BillDanmuEntity.internal_static_com_github_catvod_bean_bili_Danmus_descriptor;
      }

      @Override
      public Danmus getDefaultInstanceForType() {
        return Danmus.getDefaultInstance();
      }

      @Override
      public Danmus build() {
        Danmus result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public Danmus buildPartial() {
        Danmus result = new Danmus(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(Danmus result) {
        if (danmusBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            danmus_ = java.util.Collections.unmodifiableList(danmus_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.danmus_ = danmus_;
        } else {
          result.danmus_ = danmusBuilder_.build();
        }
      }

      private void buildPartial0(Danmus result) {
        int from_bitField0_ = bitField0_;
      }

      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Danmus) {
          return mergeFrom((Danmus)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Danmus other) {
        if (other == Danmus.getDefaultInstance()) return this;
        if (danmusBuilder_ == null) {
          if (!other.danmus_.isEmpty()) {
            if (danmus_.isEmpty()) {
              danmus_ = other.danmus_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureDanmusIsMutable();
              danmus_.addAll(other.danmus_);
            }
            onChanged();
          }
        } else {
          if (!other.danmus_.isEmpty()) {
            if (danmusBuilder_.isEmpty()) {
              danmusBuilder_.dispose();
              danmusBuilder_ = null;
              danmus_ = other.danmus_;
              bitField0_ = (bitField0_ & ~0x00000001);
              danmusBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getDanmusFieldBuilder() : null;
            } else {
              danmusBuilder_.addAllMessages(other.danmus_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                Danmu m =
                    input.readMessage(
                        Danmu.parser(),
                        extensionRegistry);
                if (danmusBuilder_ == null) {
                  ensureDanmusIsMutable();
                  danmus_.add(m);
                } else {
                  danmusBuilder_.addMessage(m);
                }
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.util.List<Danmu> danmus_ =
        java.util.Collections.emptyList();
      private void ensureDanmusIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          danmus_ = new java.util.ArrayList<Danmu>(danmus_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          Danmu, Danmu.Builder, DanmuOrBuilder> danmusBuilder_;

      /**
       * <code>repeated .com.github.catvod.bean.bili.Danmu danmus = 1;</code>
       */
      public java.util.List<Danmu> getDanmusList() {
        if (danmusBuilder_ == null) {
          return java.util.Collections.unmodifiableList(danmus_);
        } else {
          return danmusBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.github.catvod.bean.bili.Danmu danmus = 1;</code>
       */
      public int getDanmusCount() {
        if (danmusBuilder_ == null) {
          return danmus_.size();
        } else {
          return danmusBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.github.catvod.bean.bili.Danmu danmus = 1;</code>
       */
      public Danmu getDanmus(int index) {
        if (danmusBuilder_ == null) {
          return danmus_.get(index);
        } else {
          return danmusBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.github.catvod.bean.bili.Danmu danmus = 1;</code>
       */
      public Builder setDanmus(
          int index, Danmu value) {
        if (danmusBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDanmusIsMutable();
          danmus_.set(index, value);
          onChanged();
        } else {
          danmusBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.github.catvod.bean.bili.Danmu danmus = 1;</code>
       */
      public Builder setDanmus(
          int index, Danmu.Builder builderForValue) {
        if (danmusBuilder_ == null) {
          ensureDanmusIsMutable();
          danmus_.set(index, builderForValue.build());
          onChanged();
        } else {
          danmusBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.github.catvod.bean.bili.Danmu danmus = 1;</code>
       */
      public Builder addDanmus(Danmu value) {
        if (danmusBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDanmusIsMutable();
          danmus_.add(value);
          onChanged();
        } else {
          danmusBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.github.catvod.bean.bili.Danmu danmus = 1;</code>
       */
      public Builder addDanmus(
          int index, Danmu value) {
        if (danmusBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDanmusIsMutable();
          danmus_.add(index, value);
          onChanged();
        } else {
          danmusBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.github.catvod.bean.bili.Danmu danmus = 1;</code>
       */
      public Builder addDanmus(
          Danmu.Builder builderForValue) {
        if (danmusBuilder_ == null) {
          ensureDanmusIsMutable();
          danmus_.add(builderForValue.build());
          onChanged();
        } else {
          danmusBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.github.catvod.bean.bili.Danmu danmus = 1;</code>
       */
      public Builder addDanmus(
          int index, Danmu.Builder builderForValue) {
        if (danmusBuilder_ == null) {
          ensureDanmusIsMutable();
          danmus_.add(index, builderForValue.build());
          onChanged();
        } else {
          danmusBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.github.catvod.bean.bili.Danmu danmus = 1;</code>
       */
      public Builder addAllDanmus(
          Iterable<? extends Danmu> values) {
        if (danmusBuilder_ == null) {
          ensureDanmusIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, danmus_);
          onChanged();
        } else {
          danmusBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.github.catvod.bean.bili.Danmu danmus = 1;</code>
       */
      public Builder clearDanmus() {
        if (danmusBuilder_ == null) {
          danmus_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          danmusBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.github.catvod.bean.bili.Danmu danmus = 1;</code>
       */
      public Builder removeDanmus(int index) {
        if (danmusBuilder_ == null) {
          ensureDanmusIsMutable();
          danmus_.remove(index);
          onChanged();
        } else {
          danmusBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.github.catvod.bean.bili.Danmu danmus = 1;</code>
       */
      public Danmu.Builder getDanmusBuilder(
          int index) {
        return getDanmusFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.github.catvod.bean.bili.Danmu danmus = 1;</code>
       */
      public DanmuOrBuilder getDanmusOrBuilder(
          int index) {
        if (danmusBuilder_ == null) {
          return danmus_.get(index);  } else {
          return danmusBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.github.catvod.bean.bili.Danmu danmus = 1;</code>
       */
      public java.util.List<? extends DanmuOrBuilder>
           getDanmusOrBuilderList() {
        if (danmusBuilder_ != null) {
          return danmusBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(danmus_);
        }
      }
      /**
       * <code>repeated .com.github.catvod.bean.bili.Danmu danmus = 1;</code>
       */
      public Danmu.Builder addDanmusBuilder() {
        return getDanmusFieldBuilder().addBuilder(
            Danmu.getDefaultInstance());
      }
      /**
       * <code>repeated .com.github.catvod.bean.bili.Danmu danmus = 1;</code>
       */
      public Danmu.Builder addDanmusBuilder(
          int index) {
        return getDanmusFieldBuilder().addBuilder(
            index, Danmu.getDefaultInstance());
      }
      /**
       * <code>repeated .com.github.catvod.bean.bili.Danmu danmus = 1;</code>
       */
      public java.util.List<Danmu.Builder>
           getDanmusBuilderList() {
        return getDanmusFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          Danmu, Danmu.Builder, DanmuOrBuilder>
          getDanmusFieldBuilder() {
        if (danmusBuilder_ == null) {
          danmusBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              Danmu, Danmu.Builder, DanmuOrBuilder>(
                  danmus_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          danmus_ = null;
        }
        return danmusBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:com.github.catvod.bean.bili.Danmus)
    }

    // @@protoc_insertion_point(class_scope:com.github.catvod.bean.bili.Danmus)
    private static final Danmus DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Danmus();
    }

    public static Danmus getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Danmus>
        PARSER = new com.google.protobuf.AbstractParser<Danmus>() {
      @Override
      public Danmus parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Danmus> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Danmus> getParserForType() {
      return PARSER;
    }

    @Override
    public Danmus getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_github_catvod_bean_bili_Danmu_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_github_catvod_bean_bili_Danmu_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_github_catvod_bean_bili_Danmus_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_github_catvod_bean_bili_Danmus_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\017BillDanmu.proto\022\033com.github.catvod.bea" +
      "n.bili\"\340\001\n\005Danmu\022\n\n\002id\030\001 \001(\003\022\020\n\010progress" +
      "\030\002 \001(\005\022\014\n\004mode\030\003 \001(\005\022\020\n\010fontsize\030\004 \001(\005\022\r" +
      "\n\005color\030\005 \001(\r\022\017\n\007midHash\030\006 \001(\t\022\017\n\007conten" +
      "t\030\007 \001(\t\022\r\n\005ctime\030\010 \001(\003\022\016\n\006weight\030\t \001(\005\022\016" +
      "\n\006action\030\n \001(\t\022\014\n\004pool\030\013 \001(\005\022\r\n\005idStr\030\014 " +
      "\001(\t\022\014\n\004attr\030\r \001(\005\022\016\n\006effect\030\026 \001(\t\"<\n\006Dan" +
      "mus\0222\n\006danmus\030\001 \003(\0132\".com.github.catvod." +
      "bean.bili.DanmuB\021B\017BillDanmuEntityb\006prot" +
      "o3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_github_catvod_bean_bili_Danmu_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_github_catvod_bean_bili_Danmu_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_github_catvod_bean_bili_Danmu_descriptor,
        new String[] { "Id", "Progress", "Mode", "Fontsize", "Color", "MidHash", "Content", "Ctime", "Weight", "Action", "Pool", "IdStr", "Attr", "Effect", });
    internal_static_com_github_catvod_bean_bili_Danmus_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_github_catvod_bean_bili_Danmus_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_github_catvod_bean_bili_Danmus_descriptor,
        new String[] { "Danmus", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
